### ISSUE TITLE
Would love to be able to toggle "follow bone" for multiple meshes at in one go

### ISSUE THREAD

**Issue by gabrielmontagne** [xbodya13/ragdoll_tools_doc#1]
... to be able to more fluidly define an animation.

**Comment by xbodya13** [comment]
You can  select meshes , then Right Click on  Follow Bone property  and choose Copy To Selected from menu

**Comment by gabrielmontagne** [comment]
Great : )  that works for me :+1

**Comment by gabrielmontagne** [comment]
@xbodya13 , one more question - probably more about blender in general, but from your docs: 

in the tutorial for switching between keyframed and ragdoll animation, at one point you add a keyframe for "animated" to all selected hit boxes -- i see your context menu has an "insert keyfarme (selected)" -- mine only says "insert keyframe" for only the active object  even though i have all hitboxes selected.

how do you do it? 
thanks!

**Comment by gabrielmontagne** [comment]
found it!, 
https://github.com/xbodya13/keyframe_selected
:trophy:
