### ISSUE TITLE
Line 364 issue with 1.4.9 - 1.4.6 when trying to enable

### ISSUE THREAD

**Issue by Jason3128** [xbodya13/ragdoll_tools_doc#16]
Every time I try to enable the addon it says that something in line 364, 126, 1050, 1027, 1006, 688, 883, and 241. I do not know why so many lines could possibly be messed up but it has something to do with an import lib bootstrap or something because it repeats, "<frozen importlib._bootstrap

![Screenshot 2024-02-25 000723](https://github.com/xbodya13/ragdoll_tools_doc/assets/161186826/5fc9e6aa-c161-4818-85d5-80e00237b266)

**Comment by xbodya13** [comment]
The problem here is only with line 1325 and it has been fixed.
Try version 1.4.10
