### ISSUE TITLE
Make Dynamic doesn't set selected objects to Dynamic

### ISSUE THREAD

**Issue by AreaDenial3D** [xbodya13/ragdoll_tools_doc#18]
Selecting hitboxes and then pressing Set Dynamic toggles the Animated property off, but doesn't toggle the Dynamic property on. It also doesn't react weather the frame has been keyed or not. 

1.4.11; Blender 4.2 Steam LTS release.

**Comment by xbodya13** [comment]
Hi.
It's intended behavior.
**Dynamic** property is kinda redundant,it's easier to leave it always on and just switch **Animated** property when needed

**Comment by Poverizer** [comment]
Ah! That makes perfect sense. I think I just forgot that having Dynamic on by default doesn't cause any issues. Well then, let's write this off as not an issue!
