### ISSUE TITLE
bones

### ISSUE THREAD

**Issue by adsafs** [xbodya13/ragdoll_tools_doc#2]
the hit boxes it make  are not accurate i know you say in the video it does that some time but could you make a better algorithm for these kinds of models that are imported
![sad](https://user-images.githubusercontent.com/39598520/40501587-8e45e1e8-5f45-11e8-884a-d8a8e5a85d89.PNG)
 for

**Comment by adsafs** [comment]
and like make human models to please much appreciated

**Comment by xbodya13** [comment]
Current algorithm uses only bone shape to generate hitboxes  and doesn't take into account  any mesh.
So, to achieve proper hitbox shape you may adjust bones and their envelopes.

But,there is a light in the end of a tunnel.
Now i 'm working on algorithm that uses vertex groups of the attached mesh  to generate  hitboxes.

The result should looks like this:

![capture](https://user-images.githubusercontent.com/14851463/40510478-7ef89c52-5fa5-11e8-9538-4d9efab6c9ac.PNG)

**Comment by xbodya13** [comment]
And it's done.
Since version 1.2 Ragdoll Tools has this feature.

**Comment by adsafs** [comment]
can you pls send me 1.2 download my blender market wont let me sign in 😭😢

**Comment by xbodya13** [comment]
Maybe some bug..if you still can't sign in ,send me your email .

**Comment by adsafs** [comment]
i have a new computer can you send me the addon please

**Comment by xbodya13** [comment]
Send me your email to this address
xbodya13@gmail.com
